version: "3.7"

services:
    matrix:
        container_name: matrix
        image: matrixdotorg/synapse:v1.44.0
        user: "1000:1000"
        restart: on-failure
        stop_grace_period: 1m
        entrypoint: "bash"
        command: "-c './start.py generate && ./start.py migrate_config && exec ./start.py'"
        volumes:
            - ${PWD}/synapse:/data
        environment:
            UID: "1000"
            GID: "1000"
            SYNAPSE_SERVER_NAME: "matrix.nolim1t.co"
            SYNAPSE_REPORT_STATS: "no"
            SYNAPSE_NO_TLS: "yes"
        network_mode: "host"
